### ISSUE TITLE
SyntaxError: Unexpected Token

### ISSUE THREAD

**Issue by michaeljhopkins** [crispymtn/crispyfi#10]
I'm getting the below error. Any thoughts how I may be able to resolve it?

![](http://i.imgur.com/5InoVtd.png)

**Comment by dkoch** [comment]
Could you post the contents of your `config.json` (without your Slack tokens, if you've already entered them)? 

It's probably just a missing comma or something like that.

**Comment by sihil** [comment]
There is an extraneous comma in the master version of `config.json` (after the spotify password).

**Comment by sihil** [comment]
There is also a comment accidentally split over two lines in lib/spotify_handler.coffee line 123.

**Comment by dkoch** [comment]
Thanks for pointing out both problems, they should be fixed now.

**Comment by sihil** [comment]
Thanks @dkoch. I had some other problems getting it running, but will raise a PR with some suggested changes. Part of it is because I'm installing on a RPi2, which it turns out isn't quite as backwards compatible as they like to make out.
