### ISSUE TITLE
No output when I run npm start

### ISSUE THREAD

**Issue by BrandonMathis** [crispymtn/crispyfi#15]
Ran `npm start` and receive no output in the command line

I'm trying to run this on my OSX machine

I've got a `spotify_appkey.key` in the repos root and I've filled in the configs in the `config.json`

Is there something anyone can do to help?

**Comment by dkoch** [comment]
Can you check if `node index` works?
`npm start` should work as well, but our Raspberry also doesn't like it at times.

**Comment by BrandonMathis** [comment]
`node index` works well :)
